### PR TITLE
Picture description line break

### PR DESCRIPTION
**Pull request by keyakoto**
Picture description line break
**그림 2.** 데이터 집합, 활동, 파이프라인 및 연결된 서비스 간의 관계

### CODE REVIEW

**Comment by v-radelg** [comment]
Hi @keyakoto , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @keyakoto , we are still in discussing, will update the decision later soon.
See: https://github.com/MicrosoftDocs/azure-docs-pr/pull/19814

Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @keyakoto , we are still in discussing, will update the decision later soon.
See: MicrosoftDocs/azure-docs-pr#19814

Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@keyakoto  Thank you for your feedback and suggestion! 
  
  We found contribution is pure formatting correction which is not fully aligned to our acceptance criterial, I am closing this PR. 
See further references here:  MicrosoftDocs/azure-docs-pr#19814
  
  Microsoft C&E Localization Team

**Pull request closed without merging**
